name: 'Azure Static Website'
description: 'Deploy files to Azure Blob Storage Container using a connection string'
inputs:

  storage-account-name:
    description: 'The name of the Azure Storage Account. Make sure to call az login before this step, or provide a value for storage-account-key'
    required: false
  storage-account-key:
    description: 'One of the two shared keys of the storage account'
    required: false

  connection-string:
    description: 'Connection String of the Azure Storage Container'
    required: false

  blob-container-name:
    description: 'Name of the Blob Container Storage'
    required: false
  public-access-policy: 
    description: 'Access Policy to update in the Container (container | blob | <none>). For private containers do not specity any value.'
    required: false
  enabled-static-website:
    description: 'Enabled static website'
    required: false
  index-file:
    description: 'Index file for the static website'
    required: false
  error-file:
    description: '404 Error file for the static website'
    required: false
  remove-existing-files:
    description: 'If the existing files should be removed before uploading the new files'
    required: false

  folder:
    description: 'Folder containing the files to be uploaded to the Storage Container'
    required: false
    default: '.'

branding:
  icon: 'upload-cloud'
  color: blue
runs:
  using: 'node16'
  main: 'dist/index.js'
